#!/usr/bin/env python3
import argparse
import json
import os
import subprocess
import sys


def run_terraform_output(tf_dir: str) -> dict:
    try:
        result = subprocess.run(
            ["terraform", "output", "-json"],
            cwd=tf_dir,
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        raise RuntimeError("terraform not found in PATH")
    except subprocess.CalledProcessError as exc:
        stderr = (exc.stderr or "").strip()
        raise RuntimeError(f"terraform output failed in {tf_dir}: {stderr}")
    try:
        return json.loads(result.stdout or "{}")
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"failed to parse terraform output JSON in {tf_dir}: {exc}")


def get_output(outputs: dict, key: str) -> str:
    if key not in outputs:
        raise RuntimeError(f"missing terraform output: {key}")
    value = outputs[key].get("value")
    if isinstance(value, list):
        return str(value[0]) if value else ""
    return str(value)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Ansible inventory from Terraform outputs.")
    parser.add_argument("--windows-10-dir", required=True)
    parser.add_argument("--windows-server-dir", required=True)
    parser.add_argument("--domain-controller-dir", required=True)
    parser.add_argument("--inventory-path", required=True)
    parser.add_argument("--print-env", action="store_true", help="Print KEY=VALUE lines for shell eval.")
    args = parser.parse_args()

    ansible_user = os.getenv("ANSIBLE_USER", "ansible")
    ansible_password = os.getenv("ANSIBLE_PASSWORD", "").strip()
    ansible_port = os.getenv("ANSIBLE_PORT", "22")
    ansible_shell_type = os.getenv("ANSIBLE_SHELL_TYPE", "powershell")
    ansible_connection = os.getenv("ANSIBLE_CONNECTION", "ssh")

    ws_outputs = run_terraform_output(args.windows_10_dir)
    srv_outputs = run_terraform_output(args.windows_server_dir)
    dc_outputs = run_terraform_output(args.domain_controller_dir)

    windows_ws_ip = get_output(ws_outputs, "windows_ws_ip")
    windows_server_ip = get_output(srv_outputs, "windows_server_ip")
    dc_ip = get_output(dc_outputs, "dc_ip")

    password_value = ansible_password if ansible_password else "PUT-YOUR-PASSWORD-HERE"

    lines = [
        "---",
        "# Auto-generated by generate_inventory.py. Do not edit manually.",
        "",
        "all:",
        "  children:",
        "    windows_workstation:",
        "      hosts:",
        "        windows-10:",
        f"          ansible_host: {windows_ws_ip}",
        f"          ansible_connection: {ansible_connection}",
        f"          ansible_user: {ansible_user}",
        f"          ansible_password: \"{password_value}\"",
        f"          ansible_shell_type: {ansible_shell_type}",
        f"          ansible_port: {ansible_port}",
        "",
        "    windows_server:",
        "      hosts:",
        "        windows-server:",
        f"          ansible_host: {windows_server_ip}",
        f"          ansible_connection: {ansible_connection}",
        f"          ansible_user: {ansible_user}",
        f"          ansible_password: \"{password_value}\"",
        f"          ansible_shell_type: {ansible_shell_type}",
        f"          ansible_port: {ansible_port}",
        "",
        "    domain_controller:",
        "      hosts:",
        "        dc:",
        f"          ansible_host: {dc_ip}",
        f"          ansible_connection: {ansible_connection}",
        f"          ansible_user: {ansible_user}",
        f"          ansible_password: \"{password_value}\"",
        f"          ansible_shell_type: {ansible_shell_type}",
        f"          ansible_port: {ansible_port}",
    ]

    inventory_dir = os.path.dirname(os.path.abspath(args.inventory_path))
    if inventory_dir and not os.path.isdir(inventory_dir):
        os.makedirs(inventory_dir, exist_ok=True)

    with open(args.inventory_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    if args.print_env:
        print(f"WINDOWS_WS_IP={windows_ws_ip}")
        print(f"WINDOWS_SERVER_IP={windows_server_ip}")
        print(f"DC_IP={dc_ip}")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(2)
